@startuml C4Context
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
HIDE_STEREOTYPE()

title Context level

Person(httpClient, "HTTP(S) Client", "Browser, REST, gRPC, or WebSocket client")
Person(tcpClient, "TCP Client", "SSH, MySQL, or other TCP clients")
Person(udpClient, "UDP Client", "DNS resolver, QUIC, or game client")

System_Ext(downstream, "Downstream","HTTP/gRPC/TCP/UDP services")

System_Boundary(proxySystem, "Vakil") {
    System(proxyDataPlane, "Proxying logic core", "Handles HTTP routing, TCP/UDP forwarding")
    System(runtime, "Runtime", "Plugins are loaded at startup")
}

System_Ext(pluginModules, "Plugin Modules", "Middleware, routing hooks, L4 filters loaded at startup")

Rel(pluginModules, runtime, "Loaded by")

Rel(httpClient, proxyDataPlane, "HTTP/HTTPS")
Rel(tcpClient, proxyDataPlane, "TCP streams (SNI or port routing)")
Rel(udpClient, proxyDataPlane, "UDP datagrams")

Rel(runtime, proxyDataPlane, "Evaluates rules, filters and config defined in loaded plugins")

Rel(proxyDataPlane, downstream,"Forward proxied traffic\nHTTP / gRPC / TCP / UDP")

@enduml
